# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f5f55dd98b47fb1b228b86554bd871704c216ec7f067965709b76338766cbc460040dd4aa46a8ad80f25b7796ff7f2e636801c0e97e333a9530220ab736f17

test:
  secret_key_base: de77f475636691f3d720c2285a7be448d2580ea662ee1e5c92c1f757fc68b11d91b6e074d3268ba110157667949a3567e2e7a973024b02412171c87c349b10b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
